FROM python:3
ENV PYTHONBUFFERED 1
RUN mkdir -p /app
WORKDIR /app
COPY requirements.txt /app
RUN pip install -r requirements.txt
EXPOSE 8000
COPY  . /app/
CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]